### ISSUE TITLE
Tests failing, although credentials are correct

### ISSUE THREAD

**Issue by BeOleg** [AlexCline/upctoasin.com#1]
^Cubuntu@ip-172-31-36-91:~/upctoasin.com$ make test

  UPCtoASIN.com -- Amazon Lookup Module
    #lookup()
Error: [object Object]

```
  1) returns the correct ASIN for a known UPC (AWS)
```

Error: [object Object]

```
  2) returns an error for a UPC with multiple items (AWS)
```

Error: [object Object]

```
  3) returns an error for a UPC with no items (AWS)
#getLastReqTime()
  ✓ returns a timestamp 
#setLastReqTime()
  ✓ returns a timestamp 
#getConfig()
  ✓ has a non-null config object 
  ✓ has a valid log file location 
  ✓ has a valid dbpath 
#getAWSCredentials() (AWS)
  ✓ has a non-null creds object 
  ✓ has a valid AWSAccessKeyId value 
  ✓ has a valid AWSSecretKey value 
  ✓ has a valid AWSTagId value 
```

  UPCtoASIN.com -- SQLite Caching Module
    #lookup()
      ✓ returns null when looking up a UPC not in the db 
      ✓ returns the ASIN of a UPC in the db 
    #cleanup()
      ✓ removes the test UPC/ASIN from the db 
    #cache()
      ✓ returns an error when saving a duplicate UPC/ASIN to the db 
      ✓ returns a non-null object when saving a UPC/ASIN to the db 
    #getConfig()
      ✓ has a non-null config object 
      ✓ has a valid database path 
      ✓ has a valid test UPC 
      ✓ has a valid test ASIN 

  18 passing (3s)
  3 failing

  1) UPCtoASIN.com -- Amazon Lookup Module #lookup() returns the correct ASIN for a known UPC (AWS):
     Uncaught TypeError: Cannot read property 'Error' of undefined
      at /home/ubuntu/upctoasin.com/lib/amazon.js:42:58
      at /home/ubuntu/upctoasin.com/node_modules/apac/lib/OperationHelper.js:86:17
      at Parser.<anonymous> (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:384:20)
      at Parser.EventEmitter.emit (events.js:95:17)
      at Object.onclosetag (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:348:26)
      at emit (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
      at emitNode (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
      at closeTag (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
      at Object.write (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
      at Parser.exports.Parser.Parser.parseString (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:403:31)
      at Parser.parseString (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:6:61)
      at Object.exports.parseString (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:433:19)
      at IncomingMessage.<anonymous> (/home/ubuntu/upctoasin.com/node_modules/apac/lib/OperationHelper.js:84:20)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickCallback (node.js:415:13)

  2) UPCtoASIN.com -- Amazon Lookup Module #lookup() returns an error for a UPC with multiple items (AWS):
     Uncaught TypeError: Cannot read property 'Error' of undefined
      at /home/ubuntu/upctoasin.com/lib/amazon.js:42:58
      at /home/ubuntu/upctoasin.com/node_modules/apac/lib/OperationHelper.js:86:17
      at Parser.<anonymous> (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:384:20)
      at Parser.EventEmitter.emit (events.js:95:17)
      at Object.onclosetag (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:348:26)
      at emit (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
      at emitNode (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
      at closeTag (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
      at Object.write (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
      at Parser.exports.Parser.Parser.parseString (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:403:31)
      at Parser.parseString (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:6:61)
      at Object.exports.parseString (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:433:19)
      at IncomingMessage.<anonymous> (/home/ubuntu/upctoasin.com/node_modules/apac/lib/OperationHelper.js:84:20)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickCallback (node.js:415:13)

  3) UPCtoASIN.com -- Amazon Lookup Module #lookup() returns an error for a UPC with no items (AWS):
     Uncaught TypeError: Cannot read property 'Error' of undefined
      at /home/ubuntu/upctoasin.com/lib/amazon.js:42:58
      at /home/ubuntu/upctoasin.com/node_modules/apac/lib/OperationHelper.js:86:17
      at Parser.<anonymous> (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:384:20)
      at Parser.EventEmitter.emit (events.js:95:17)
      at Object.onclosetag (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:348:26)
      at emit (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
      at emitNode (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
      at closeTag (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
      at Object.write (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
      at Parser.exports.Parser.Parser.parseString (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:403:31)
      at Parser.parseString (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:6:61)
      at Object.exports.parseString (/home/ubuntu/upctoasin.com/node_modules/apac/node_modules/xml2js/lib/xml2js.js:433:19)
      at IncomingMessage.<anonymous> (/home/ubuntu/upctoasin.com/node_modules/apac/lib/OperationHelper.js:84:20)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickCallback (node.js:415:13)

Any idea?

**Comment by namanshenoy** [comment]
Hi! Great piece of code!
Not sure how to get tagID, though. Any help please?
